Todo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('doing.urls', "doing"), namespace="doing"))
]

doing/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='index'),
    path('todonext', views.what_todo,name='todonext'),
    path('complete/<id>', views.completeTodo, name='complete'),
    path('deletecompleted', views.deletecompleted, name='deletecompleted'),
    path('deleteall', views.deleteall, name='deleteall'),
    path('delete/<id>', views.delete, name='delete'),
    path('edit/<id>', views.editing, name='edit'),
    path('update<id>',views.update, name='update')
]

doing/models.py
from django.db import models
class Todo(models.Model):
    text=models.CharField(max_length=100)
    complete=models.BooleanField(default=False)

    def __str__(self):
        return self.text

doing/views.py
from django.shortcuts import render, redirect
from .models import Todo
from django.views.decorators.http import require_POST
from .form import TodoForm
from django.http import HttpResponse

def index(request):
    what=Todo.objects.order_by('id')
    form=TodoForm()
    return render(request, 'index.html', {"what":what, "form":form})

def what_todo(request):
    if request.method=='POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            print(form)
            new=Todo(text=request.POST['text'])
            new.save()
    return redirect('doing:index')

def completeTodo(request, id):
    todo=Todo.objects.get(pk=id)
    todo.complete = True
    todo.save()

    return redirect('doing:index')

def deletecompleted(request):
    Todo.objects.filter(complete__exact=True).delete()
    return redirect('doing:index')
def deleteall(request):
    Todo.objects.all().delete()
    return redirect('doing:index')
def delete(request,id):
    item=Todo.objects.get(pk=id)
    item.delete()
    return redirect('doing:index')
def editing(request, id):
    item = Todo.objects.get(pk=id)
    print(item)
    form = TodoForm(request.POST)
    return render(request,'update.html',{'item':item,'form':form})
def update(request, id):
    if request.method=='POST':
        form=TodoForm(request.POST)
        if form.is_valid():
            todo_item = Todo.objects.get(id=id)
            todo_item.text = request.POST['text']
            todo_item.save()
            print("not working")
            return redirect('doing:index')
        else:
            return redirect('doing:editing')

doing/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>it is working</h1>
<form action="todonext" method="POST">
    {% csrf_token %}
    {{ form.text }}
    <input type="submit" name="submit" value="Submit">
    <a href="{% url 'doing:deletecompleted' %}"> <button type="button">Delete Completed</button></a>
    <a href="{% url 'doing:deleteall' %}"> <button type="button">Delete all</button></a>
</form>

<ul>
{% for element in what %}
{#    {% if element.complete %}#}
{#    <li {{ element.text }}></li>#}
{#    {% else %}#}
{#    <a href="#" <li {{ element.text }}></li> </a>#}
{#    {% endif %}#}
    {% if element.complete %}
   <li>{{ element.text }}</li>
        {% else %}
      <a href="{% url 'doing:complete' element.id %}" >
          <li>{{ element.text }}<a href="{%url 'doing:delete' element.id %}"> <button type="button">Delete</button></a>
          <a href="{%url 'doing:edit' element.id%}"> <button type="button">edit</button></a></li></li>

      </a>
    {% endif %}
{% endfor %}

</ul>
</body>
</html>

doing/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="{% url 'doing:update' item.id %}" novalidate>
  {% csrf_token %}
  {{ form }}
    <a href=""> <button type="submit">Submit</button></a>
</form>
</body>
</html>